import { QyCD } from "./QyCD.ts";
export declare class QyBatch extends QyCD {
    fileLogLevel: any;
    actionQueue: any;
    changeId: any;
    changeList: any;
    syncList: any;
    qyAclCmdGenerator: any;
    qyCmdObjHistory: any;
    constructor(qyCache?: any, options?: any);
    createDir(namePath: any, parentDir?: any): any;
    createDirP(namePath: any, parentDir?: any): any;
    delDir(namePath: any, parentDir?: any): any;
    delDirP(namePath: any, parentDir?: any): any;
    createFile(namePath: any, parentDir?: any): any;
    createFileP(namePath: any, parentDir?: any): any;
    delFile(namePath: any, parentDir?: any): any;
    delFileP(namePath: any, parentDir?: any): any;
    createIndex(indexHostDirNamePath: any, indexPropPathList: any, parentDir?: any): any;
    createIndexP(indexHostDirNamePath: any, indexPropPathList: any, parentDir?: any): any;
    delIndex(indexHostDirNamePath: any, indexPropPath: any, parentDir?: any): any;
    delIndexP(indexHostDirNamePath: any, indexPropPath: any, parentDir?: any): any;
    insert(namePath: any, content: any, parentDir?: any): any;
    insertP(namePath: any, content: any, parentDir?: any): any;
    remove(namePath: any, content: any, parentDir?: any): any;
    removeP(namePath: any, content: any, parentDir?: any): any;
    replace(namePath: any, content: any, parentDir?: any): any;
    replaceP(namePath: any, content: any, parentDir?: any): any;
    delContent(namePath: any, parentDir?: any): any;
    delContentP(namePath: any, parentDir?: any): any;
    insertTrigger(triggerName: any, fileNamePath: any, propNamePathList: any, modCode: any): any;
    removeTrigger(triggerName: any): any;
    insertRpc(rpcFunName: any, modCode: any): any;
    removeRpc(rpcFunName: any): any;
    run(needPromise?: boolean): any;
    getTopHistoryCmdObj(): any;
    _action_insertTrigger(action: any): boolean;
    _action_removeTrigger(action: any): boolean;
    _action_insertRpc(action: any): boolean;
    _action_removeRpc(action: any): boolean;
    _action_createIndex(action: any): void;
    _action_delIndex(action: any): void;
    _action_delFile(action: any, deletingParentDir?: boolean): boolean;
    _action_delDir(action: any): boolean;
    _action_delContent(action: any): boolean;
    _action_insert(action: any): boolean;
    _action_createFile(action: any): boolean;
    _action_createDir(action: any): boolean;
}
