import EventEmitter from "node:events";
import { QyDir } from "./QyDir.ts";
import type { QyFile } from "./QyFile.ts";
export declare class QyCache extends EventEmitter {
    rootFolder: any;
    options: any;
    qyDB: any;
    kvFolder: any;
    rpcFolder: any;
    rootDir: any;
    triggerRootDir: any;
    rpcRootDir: any;
    indexRootDir: any;
    exclusiveFilePath: any;
    qyKVData: any;
    qyFileLogger: any;
    rpcFunMap: {};
    constructor(rootFolder: string, options?: any, qyDB?: any);
    start(): Promise<this>;
    stop(): Promise<this>;
    increaseChangeId(): any;
    decreaseChangeId(): void;
    save(changeId: any, cmdArgAsListObj: any, logText: any, syncList: any, needPromise: any): any;
    getFile(namePath: QyFile | string | string[], parentDir?: any): QyFile | undefined;
    getDir(namePath: QyDir | string | string[], parentDir?: any): QyDir | undefined;
    getOrCreateFile(namePath: QyFile | string | string[], parentDir?: any): QyFile;
    getOrCreateDir(namePath: QyDir | string | string[], parentDir?: any): QyDir;
    getIndexDir(indexHostDir: QyDir): any;
    getOrCreateIndexDir(indexHostDir: any): any;
    getTriggerFile(triggerName: any): any;
    getOrCreateTriggerFile(triggerName: any): any;
    get triggerFileList(): any;
    getRpcFile(rpcFunName: any): any;
    getOrCreateRpcFile(rpcFunName: any): any;
    get rpcFileList(): any;
    insertTriggerToTree(triggerName: any, fileNamePath: any, propNamePathList: any, modCode: any): void;
    removeTriggerFromTree(triggerName: any, fileNamePath: any): void;
    insertRpc(rpcFunName: any, modCode: any): void;
    removeRpc(rpcFunName: any): void;
    queryFiles(indexHostDirNamePath: any, queryObj: any, limit: any, cursor: any, parentDir?: any): never[];
    queryFilesMulti(indexHostDirNamePathMulti: any, limit: any, cursor: any, parentDir?: any): never[];
    callRpc(rpcFunName: any, args: any, body: any): Promise<any>;
}
