import { QyCD } from "./QyCD.ts";
import type { QyDir } from "./QyDir.ts";
import type { QyFile } from "./QyFile.ts";
export declare class QyDB extends QyCD {
    rootFolder: string;
    options: {};
    fetch: any;
    batch: any;
    _immediate: any;
    constructor(rootFolder?: string, options?: {});
    start(options?: {}): Promise<this>;
    stop(): Promise<void>;
    createDir(namePath: string | string[]): QyDir;
    createDirP(namePath: string | string[]): QyDir;
    createFile(namePath: string | string[]): QyFile;
    createFileP(namePath: string | string[]): QyFile;
    createIndex(indexHostDirNamePath: string | string[] | QyDir, indexPropPathList: string[] | string[][]): any;
    createIndexP(indexHostDirNamePath: string | string[] | QyDir, indexPropPathList: string[][]): any;
    delIndex(indexHostDirNamePath: string | string[] | QyDir, indexPropPath: string | string[]): any;
    delIndexP(indexHostDirNamePath: any, indexPropPath: any): any;
    insert(namePath: any, content: any): any;
    insertP(namePath: any, content: any): any;
    remove(namePath: any, content: any): any;
    removeP(namePath: any, content: any): any;
    replace(namePath: any, content: any): any;
    replaceP(namePath: any, content: any): any;
    delDir(namePath: any): any;
    delDirP(namePath: any): any;
    delFile(namePath: any): any;
    delFileP(namePath: any): any;
    delContent(namePath: any): any;
    delContentP(namePath: any): any;
    insertTrigger(triggerName: any, fileNamePath: any, propNamePathList: any, modCode: any): any;
    removeTrigger(triggerName: any): any;
    insertRpc(rpcFunName: any, modCode: any): any;
    removeRpc(rpcFunName: any): any;
    on(eventName: any, listener: any): any;
    callRpc(rpcFunName: any, args: any, body?: undefined): any;
}
