import { QyItem } from "./QyItem.ts";
import { QyFile } from "./QyFile.ts";
import type { QyCache } from "./QyCache.ts";
export declare class QyDir extends QyItem {
    _subdirCount: number;
    _fileCount: number;
    subdirMapChangeCount: number;
    fileMapChangeCount: number;
    dChangeId: number;
    fChangeId: number;
    cache: {};
    constructor(name: string | number, created?: boolean, parentDir?: QyDir | undefined, qyCache?: QyCache | undefined);
    get created(): boolean;
    set created(val: boolean);
    get fileCount(): number;
    get subdirCount(): number;
    get isDir(): boolean;
    get isEmpty(): boolean;
    get isHiddenFolder(): boolean;
    get subdirMapKey(): string;
    get fileMapKey(): string;
    get subdirMap(): {};
    get fileMap(): {};
    getSubdir(name: string): QyDir | undefined;
    getFile(fileName: string): QyFile | undefined;
    getOrCreateSubdir(name: string, created?: boolean): QyDir;
    getOrCreateFile(fileName: string, created?: boolean): QyFile;
    searchSubdir(namePath: string[], endIdx?: number): QyDir | undefined;
    searchOrCreateSubdir(namePath: string[], created?: boolean, endIdx?: number): QyDir;
    searchFile(namePath: string[]): QyFile | undefined;
    searchOrCreateFile(namePath: string[], created?: boolean): QyFile;
    get subdirList(): QyDir[];
    get subdirNameList(): string[];
    get sortedSubdirList(): QyDir[];
    get sortedSubdirNameList(): string[];
    get fileList(): QyFile[];
    get fileNameList(): string[];
    get sortedFileList(): QyFile[];
    get sortedFileNameList(): string[];
    allSubdirs(): any;
    allLeafSubdirs(): Generator<any, void, unknown>;
    allFiles(): Generator<any, void, unknown>;
    allLoadedSubdirs(): any;
    setChildTriggerNodes(child: QyDir): void;
    filterSubdirNames(filterFun: any): Generator<QyDir, void, unknown>;
    compareSubdirRangeL2H(cmpFun: any): Generator<QyDir, void, unknown>;
    compareSubdirRangeH2L(cmpFun: any): Generator<QyDir | undefined, void, unknown>;
}
