export declare const __dirname: string;
export declare const SpecialOperators: {
    [k: string]: string;
};
export declare const SpecialFilePaths: {
    HiddenFolderName: string;
    TriggerDirPath: string[];
    RpcDirPath: string[];
    IndexDirPath: string[];
    IndexPropPathsFileName: string;
};
export declare function isMatchName(name: any): any;
export declare function getMatchParam(name: any): any;
export declare function getSizeStr(size: number): string;
export declare function calHash(str: any, len?: number): string;
export declare const Hash_Key_Length: number;
export declare function getSubdirMapKey(fullPathHash: any): string;
export declare function getFileMapKey(fullPathHash: any): string;
export declare function getContentKey(fullPathHash: any): string;
export declare function getRandomStr(byteCount?: number): string;
export declare function arrayLast(array: any): any;
export declare function isEmptyObj(obj: any): boolean;
export declare function isNotNullObj(item: any): boolean;
export declare function isString(item: any): item is string;
export declare function isNumber(item: any): item is number;
export declare function isBoolean(item: any): item is boolean;
export declare function isFunction(item: any): boolean;
export declare function isSimpleType(item: any): boolean;
export declare function trimArrayTail(arr: any): any;
export declare function setPromise(operation: any): any;
export declare function toBuffer(data: any): Buffer<any>;
export declare function getSuffix(num: any): "" | "s";
export declare function ensureDir(dirPath: any): Promise<string | undefined>;
export declare function ensureParentDir(filePath: any): Promise<string | undefined>;
export declare function getSize(filePath: any): Promise<number | false>;
export declare function folderOrFileExists(folderPath: any): Promise<boolean>;
export declare function sleep(seconds: number, signal?: undefined): Promise<boolean> | Promise<void>;
export declare function lockExclusiveFilePath(exclusiveFilePath: any): Promise<void>;
export declare function unlockExclusiveFilePath(exclusiveFilePath: any): void;
export declare function fromSingleName(name: any): any;
export declare function toSingleName(list: any): any;
export declare function pathSplit(itemPath: any): any;
export declare function propNameSplit(propNameStr: any): any;
export declare function propNameJoin(propName: any): any;
export declare function randomInt(max: any, min?: number): number;
export declare function listToMap(list: any): {};
export declare function readBufferAsync(filePath: any, fileHandle: any, start: any, length: any): Promise<Buffer<ArrayBuffer> | undefined>;
export declare function memoryPercent(): number;
export declare function loadFileList(fileList: any, preloadCount?: number): AsyncGenerator<{
    filePath: any;
    bin: any;
}, void, unknown>;
export * as default from "./QyUtils.ts";
